spring:
  application:
    name: jc-bot-worker

server:
  port: ${SERVER_PORT:8081}

bot:
  server-url: ${SERVER_URL:ws://localhost:8080/ws}
  backend-http-url: ${BACKEND_HTTP_URL:http://localhost:8080}
  bot-username: ${BOT_USERNAME:bot-worker}
  bot-password: ${BOT_PASSWORD:Bot@worker1}
